version = "3.9.8"
runner.dialect = scala213

maxColumn = 120
indent.main = 2
indent.significant = 2
indent.ctrlSite = 4
indent.defnSite = 2
indent.callSite = 2

align.preset = more
align.multiline = false

continuationIndent.defnSite = 2
continuationIndent.ctrlSite = 2
continuationIndent.callSite = 2

newlines.topLevelStatements = [before,after]
newlines.topLevelStatementsMinBreaks = 2
newlines.implicitParamListModifierPrefer = before

rewrite.rules = [SortImports, RedundantBraces, RedundantParens]
rewrite.sortModifiers.order = ["implicit", "final", "sealed", "abstract", "override", "private", "protected", "lazy"]

spaces.inImportCurlyBraces = false
spaces.beforeContextBoundColon = Always

docstrings.style = Asterisk
docstrings.oneline = keep
docstrings.wrap = no

project.git = true
project.excludeFilters = [
  target/
  simWorkspace/
]
